version: "3.8"
services:
  load:
    build: 
      context: ./src
      dockerfile: load/Dockerfile
    env_file: 
      - .env
    volumes:
      - ./.data:/.data
      - ./files:/files
    environment:
      - PYTHONUNBUFFERED=1
      - FORCE_LOAD=${FORCE_LOAD:-false}  # Add this line
  api:
    build:
      context: ./src
      dockerfile: api/Dockerfile
    ports:
      - "3100:3100"
      - "5678:5678"  # debugpy port
    env_file: 
      - .env
    command: /bin/sh -c "[ '${DEBUG_MODE:-0}' = '1' ] && exec python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn api.api.app:app --host 0.0.0.0 --port 3100 --proxy-headers || exec uvicorn api.api.app:app --host 0.0.0.0 --port 3100 --proxy-headers"
    volumes:
      - ./src/:/code/
      - ./.data:/.data
    depends_on:
      - load
    environment:
      - PYTHONUNBUFFERED=1
  web:
    build:
      context: ./src/web
    ports:
      - "3000:3000"
    depends_on:
      - api
