apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
spec:
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
        - name: load
          image: {{.Env.SERVICE_LOAD_IMAGE_NAME}}
          env:
            - name: AZURE_CLIENT_ID
              value: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
            - name: AZURE_OPENAI_API_KEY
              value: {{.Env.AZURE_OPENAI_API_KEY}}
            - name: AZURE_OPENAI_API_VERSION
              value: {{.Env.AZURE_OPENAI_API_VERSION}}
            - name: AZURE_OPENAI_DEPLOYMENT_NAME
              value: {{.Env.AZURE_OPENAI_DEPLOYMENT_NAME}}
            - name: AZURE_OPENAI_ENDPOINT
              value: {{.Env.AZURE_OPENAI_ENDPOINT}}
            - name: AZURE_OPENAI_API_KEY
              value: {{.Env.AZURE_OPENAI_API_KEY}}
            - name: AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME
              value: {{.Env.AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME}}
            - name: AZURE_OPENAI_EMBEDDINGS_MODEL_NAME
              value: {{.Env.AZURE_OPENAI_EMBEDDINGS_MODEL_NAME}}
            - name: AZURE_SEARCH_ENDPOINT
              value: {{.Env.AZURE_SEARCH_ENDPOINT}}
            - name: AZURE_SEARCH_API_KEY
              value: {{.Env.AZURE_SEARCH_API_KEY}}
            - name: AZURE_SEARCH_INDEX_NAME
              value: {{.Env.AZURE_SEARCH_INDEX_NAME}}
            - name: VECTORDB_TYPE
              value: {{.Env.VECTORDB_TYPE}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"